### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Fuffy-Katons** [sashafiesta/create-connected-fabric#1]
The game crashes with the mod installed. The only mods installed are [Create] and [Create: Connected Fabric]. 

Minecraft Version 1.20.1

Fabric Version 1.15.8 / 1.15.9 / 1.15.10 (Tried all 3 none worked)

Attached the crash report in case it helps.

[crash-2024-04-25_13.25.56-client.txt](https://github.com/sashafiesta/create-connected-fabric/files/15108273/crash-2024-04-25_13.25.56-client.txt)

**Comment by sashafiesta** [comment]
Thank you for your report
IDK why but my mod fails to apply mixin to create-0.5.1fb1417, but it works ok with create-0.5.1fb1335
Most likely it is a target error.
I'll try to fix it today
Thanks!

**Comment by sashafiesta** [comment]
An official version from modrinth doesn't work too
Only that one: https://mvn.devos.one/snapshots/com/simibubi/create/create-fabric-1.20.1/0.5.1-f-build.1335+mc1.20.1/create-fabric-1.20.1-0.5.1-f-build.1335+mc1.20.1.jar
But again, I'll fix it soon

**Comment by sashafiesta** [comment]
Uhh... One mixin doesn't get registered in refmap for some reason. I'll try to fix it but I'm not too experienced with java :<

**Comment by 0xarch** [comment]
**Bad** that the build _from maven_ still could not launch
From launcher:
`Could not initialize class com.simibubi.create.AllBlocks`

Tried both Fabric 0.15.11 & 0.15.10

**Comment by 0xarch** [comment]
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class com.simibubi.create.AllBlocks
		at com.hlysine.create_connected.content.shearpin.ShearPinBlock$PlacementHelper.<init>(ShearPinBlock.java:117)
		at com.hlysine.create_connected.content.shearpin.ShearPinBlock.<clinit>(ShearPinBlock.java:41)
		at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:333)
		at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:44)
		at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17)
		at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121)
		at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217)
		at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189)
		at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:12)
		at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188)
		at com.hlysine.create_connected.CreateConnected.onInitialize(CreateConnected.java:32)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.foundation.block.ItemUseOverrides failed [in thread "Render thread"]
		at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:608)
		at com.simibubi.create.Create.onInitialize(Create.java:104)
		... 7 more
	Suppressed: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.foundation.block.ItemUseOverrides failed
		at uwu.lopyluna.create_dd.registry.DDBlocks.<clinit>(DDBlocks.java:643)
		at uwu.lopyluna.create_dd.DDCreate.onInitialize(DDCreate.java:24)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.foundation.block.ItemUseOverrides failed
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
		... 9 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
		... 13 more
	Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [create_connected.mixins.json:ItemUseOverridesMixin from mod create_connected] from phase [DEFAULT] in config [create_connected.mixins.json] FAILED during APPLY
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
		... 16 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @WrapOperation annotation on preciseHitLocation could not find any targets matching 'onBlockActivated(Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;)Lnet/minecraft/world/InteractionResult;' in com.simibubi.create.foundation.block.ItemUseOverrides. Using refmap create_connected-refmap.json [PREINJECT Applicator Phase -> create_connected.mixins.json:ItemUseOverridesMixin from mod create_connected -> Prepare Injections ->  -> wrapOperation$zma000$create_connected$preciseHitLocation(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;Lnet/minecraft/class_2960;)Lnet/minecraft/class_1269; -> Parse]
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
		at com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:14)
		at com.llamalad7.mixinextras.injector.MixinExtrasLateInjectionInfo.<init>(MixinExtrasLateInjectionInfo.java:19)
		at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.<init>(WrapOperationInjectionInfo.java:28)
		at jdk.internal.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
		at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.<init>(SugarWrapperImpl.java:50)
		at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.<init>(WrapperInjectionInfo.java:29)
		at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.<init>(SugarWrapperInjectionInfo.java:14)
		at jdk.internal.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
		... 16 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.foundation.block.ItemUseOverrides failed
	at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:608)
	at com.simibubi.create.Create.onInitialize(Create.java:104)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.foundation.block.ItemUseOverrides failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [create_connected.mixins.json:ItemUseOverridesMixin from mod create_connected] from phase [DEFAULT] in config [create_connected.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @WrapOperation annotation on preciseHitLocation could not find any targets matching 'onBlockActivated(Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;)Lnet/minecraft/world/InteractionResult;' in com.simibubi.create.foundation.block.ItemUseOverrides. Using refmap create_connected-refmap.json [PREINJECT Applicator Phase -> create_connected.mixins.json:ItemUseOverridesMixin from mod create_connected -> Prepare Injections ->  -> wrapOperation$zma000$create_connected$preciseHitLocation(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;Lnet/minecraft/class_2960;)Lnet/minecraft/class_1269; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:14)
	at com.llamalad7.mixinextras.injector.MixinExtrasLateInjectionInfo.<init>(MixinExtrasLateInjectionInfo.java:19)
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.<init>(WrapOperationInjectionInfo.java:28)
	at jdk.internal.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.<init>(SugarWrapperImpl.java:50)
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.<init>(WrapperInjectionInfo.java:29)
	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.<init>(SugarWrapperInjectionInfo.java:14)
	at jdk.internal.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more
```
Due to **Create Fabric itself**?

**Comment by sashafiesta** [comment]
Fixed in https://github.com/sashafiesta/create-connected-fabric/commit/83f6815e7e3d63bfe0608ec74cfd04a590c5110c
Had to remove encased chain cogwheel and linked transmitter though.
